/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MrCalJNI */

#ifndef _Included_MrCalJNI
#define _Included_MrCalJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MrCalJNI
 * Method:    mrcal_calibrate_camera
 * Signature: ([D[DDDDDD)LMrCalJNI/CalResult;
 */
JNIEXPORT jobject JNICALL Java_MrCalJNI_mrcal_1calibrate_1camera
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
