/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photonvision_mrcal_MrCalJNI */

#ifndef _Included_org_photonvision_mrcal_MrCalJNI
#define _Included_org_photonvision_mrcal_MrCalJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photonvision_mrcal_MrCalJNI
 * Method:    mrcal_calibrate_camera
 * Signature: ([DIIDIID)Lorg/photonvision/mrcal/MrCalJNI/MrCalResult;
 */
JNIEXPORT jobject JNICALL Java_org_photonvision_mrcal_MrCalJNI_mrcal_1calibrate_1camera
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdouble, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
